fix: removed ttl index on created_at from all collection
hanabitech/py-protocol-layer pull request #5
Opened 2024-05-14 09:57 UTC by HtDeepMakadiya

2024-05-14 12:01 UTC, todaysolve requested changes

2024-05-14 12:01 UTC, todaysolve commented on webserver/main/models/__init__.py
>      get_mongo_collection("location").create_index([("gps", GEOSPHERE)])
Only create if they are not present...

2024-05-14 21:35 UTC, HtDeepMakadiya commented on webserver/main/config.py
> -    TTL_IN_SECONDS = int(os.getenv("TTL_IN_SECONDS", "18000"))
Checked. Not present anywhere even in .env.example.

2024-05-15 04:53 UTC, HtDeepMakadiya commented on webserver/main/models/__init__.py
>      get_mongo_collection("location").create_index([("gps", GEOSPHERE)])
fixed

2024-06-18 09:19 UTC, todaysolve commented
@HtDeepMakadiya please change ttll value to 7 days. But this PR approach is wrong, the database will always be outdated with network changes

2024-10-22 13:02 UTC, todaysolve approved these changes

2024-10-22 13:02 UTC, merged